package com.ocs.indaba.workflow

import java.util.Date;
import com.ocs.indaba.util.DateUtils;
import com.ocs.indaba.common.Constants;
import com.ocs.indaba.po.TaskAssignment;
import com.ocs.indaba.po.GoalObject;
import com.ocs.indaba.service.SiteMessageService;
import com.ocs.indaba.service.CaseService;

rule "Report task overdue 1"
    when
        ta: TaskAssignment()
        goalObject: GoalObject()
	siteMessageService: SiteMessageService()
        caseService: CaseService()
        eval(ta.getStatus() != Constants.TASK_STATUS_DONE)
        eval((new Date()).getTime()-ta.getDueTime().getTime() >= 5*(long)DateUtils.MILLISECONDS_OF_DAY)
    then
    	// System.out.println("=====<<<< REPORT TASK OVERDUE 1 >>>>======");
        siteMessageService.reportToProjectAdmin(goalObject, ta, Constants.NOTIFICATION_TYPE_ALERT1_TASK_OVERDUE);
        // caseService.openCaseForProjectAdmin(ta, "Task Overdue", Constants.NOTIFICATION_TYPE_ALERT1_TASK_OVERDUE);
end

