package com.ocs.indaba.workflow

import java.util.Date;
import com.ocs.indaba.common.Constants;
import com.ocs.indaba.po.TaskAssignment;
import com.ocs.indaba.service.SiteMessageService;

rule "Check task before due 2"
    when
        ta: TaskAssignment()
	siteMessageService: SiteMessageService()
        eval(ta.getTaskId() != -3 && ta.getTaskId() != -4)
        eval(ta.getStatus() != Constants.TASK_STATUS_DONE)
        eval(ta.getDueTime().getTime()-(new Date()).getTime() <= 2*1000*60*60*24)
    then
    	System.out.println("=====<<<< CHECK TASK BEFORE DUE 2 >>>>======");
        siteMessageService.sendTaskMessage(ta, Constants.NOTIFICATION_TYPE_REMINDER2_ABOUT_DUE);
end

