package com.ocs.indaba.workflow

import com.ocs.indaba.common.Constants;
import com.ocs.indaba.po.TaskAssignment;
import com.ocs.indaba.service.SiteMessageService;

rule "Notify Payment"
    when
        ta: TaskAssignment()
	siteMessageService: SiteMessageService()
        eval(ta.getStatus() == Constants.TASK_STATUS_DONE)
    then
    	System.out.println("=====<<<< NOTIFY PAYMENT >>>>======");
        siteMessageService.notifyAuthor(ta, Constants.NOTIFICATION_TYPE_NOTIFY_PAYMENT_SENT);
end

