package com.ocs.indaba.workflow

import com.ocs.indaba.common.Constants;
import com.ocs.indaba.po.TaskAssignment;
import com.ocs.indaba.po.Goal;
import com.ocs.indaba.po.GoalObject;
import com.ocs.indaba.service.SiteMessageService;

rule "Report Milestone Overdue"
    when
        ta: TaskAssignment()
        goal: Goal()
        goalObject: GoalObject()
	siteMessageService: SiteMessageService()
        eval((new Date()).getTime()-goalObject.getEnterTime().getTime() >= (goal.getDuration()+2)*1000*60*60*24)
    then
    	System.out.println("=====<<<< REPORT MILESTONE OVERDUE >>>>======");
        siteMessageService.reportToProjectAdmin(goalObject, ta, Constants.NOTIFICATION_TYPE_ALERT_OVERDUE);
end

