package com.ocs.indaba.workflow

import java.util.Date;
import com.ocs.indaba.util.DateUtils;
import com.ocs.indaba.common.Constants;
import com.ocs.indaba.po.TaskAssignment;
import com.ocs.indaba.po.GoalObject;
import com.ocs.indaba.service.SiteMessageService;

rule "Report task overdue 2"
    when
        ta: TaskAssignment()
        goalObject: GoalObject()
	siteMessageService: SiteMessageService()
        eval(ta.getTaskId() != -3 && ta.getTaskId() != -4)
        eval(ta.getStatus() != Constants.TASK_STATUS_DONE)
        eval((new Date()).getTime()-ta.getDueTime().getTime() >= 10*(long)DateUtils.MILLISECONDS_OF_DAY)
    then
    	System.out.println("=====<<<< REPORT TASK OVERDUE 2 >>>>======");
        siteMessageService.reportToProjectAdmin(goalObject, ta, Constants.NOTIFICATION_TYPE_ALERT2_TASK_OVERDUE);
end

