package com.ocs.indaba.workflow

import java.util.Date;
import com.ocs.indaba.util.DateUtils;
import com.ocs.indaba.common.Constants;
import com.ocs.indaba.po.Goal;
import com.ocs.indaba.po.GoalObject;
import com.ocs.indaba.dao.GoalObjectDAO;
import com.ocs.indaba.service.HorseService;
import com.ocs.indaba.service.SiteMessageService;

rule "Goal exit partial completion"
    when
        goal: Goal()
        goalObject: GoalObject()
        goalObjectDAO: GoalObjectDAO()
        horseService: HorseService()
        siteMessageService: SiteMessageService()
        eval((new Date()).getTime()-goalObject.getEnterTime().getTime() >= (goal.getDuration()+10)*(long)DateUtils.MILLISECONDS_OF_DAY)
        eval(horseService.getGoalObjectCompletedPercentage(goalObject) >= 0.8)
    then
        System.out.println("=====<<<< GOAL EXIT PARTIAL COMPLETION >>>>======");
        goalObject.setStatus((short)Constants.GOAL_OBJECT_STATUS_DONE);
        goalObject.setExitTime(new Date());
        goalObjectDAO.update(goalObject);
        siteMessageService.notifyProjectAdminGoalExit(goalObject, 100);
end