package com.ocs.indaba.workflow

import com.ocs.indaba.common.Constants;
import com.ocs.indaba.po.TaskAssignment;
import com.ocs.indaba.service.SiteMessageService;

rule "Thank User"
    when
        ta: TaskAssignment()
	siteMessageService: SiteMessageService()
        eval(ta.getTaskId() != -3 && ta.getTaskId() != -4)
        eval(ta.getStatus() == Constants.TASK_STATUS_DONE)
    then
    	System.out.println("=====<<<< THANK USER >>>>======");
        siteMessageService.sendThankUserMessage(ta);
end

